### ISSUE TITLE
start.sh script fails with errors

### ISSUE THREAD

**Issue by PeterDavidCarter** [tchoutri/Nvjorn#3]
```
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

** (Mix.Config.LoadError) could not load config config/prod.exs
    ** (File.Error) could not read file "/Users/user/Nvjorn/config/prod.exs": no such file or directory
    (elixir) lib/file.ex:272: File.read!/1
    (mix) lib/mix/config.ex:180: Mix.Config.read!/2
    (mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

** (Mix.Config.LoadError) could not load config config/prod.exs
    ** (File.Error) could not read file "/Users/user/Nvjorn/config/prod.exs": no such file or directory
    (elixir) lib/file.ex:272: File.read!/1
    (mix) lib/mix/config.ex:180: Mix.Config.read!/2
    (mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

** (Mix.Config.LoadError) could not load config config/prod.exs
    ** (File.Error) could not read file "/Users/user/Nvjorn/config/prod.exs": no such file or directory
    (elixir) lib/file.ex:272: File.read!/1
    (mix) lib/mix/config.ex:180: Mix.Config.read!/2
    (mix) lib/mix/config.ex:217: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
```

**Comment by tchoutri** [comment]
```
** (Mix.Config.LoadError) could not load config config/prod.exs
    ** (File.Error) could not read file "/Users/user/Nvjorn/config/prod.exs": no such file or directory
    (elixir) lib/file.ex:272: File.read!/1
```
You forgot to rename `config/prod.sample.exs` to `config/prod.exs` :)
